spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sso?useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    spring.druid.initialSize: 5
    spring.druid.minIdle: 5
    spring.druid.maxWait: 60000
    spring.druid.timeBetweenEvictionRunsMillis: 60000
    spring.druid.minEvictableIdleTimeMillis: 300000
